# --- Core Defaults & Constants ---

# Folders matching these names are excluded from both the project tree and content processing.
CORE_IGNORES = {
    '.git', '__pycache__', 'venv', '.vscode', '.ipynb_checkpoints',
    'node_modules', '.idea', 'dist', 'build', '.mypy_cache',
    '.pytest_cache', 'target', '.docker', '.aws', '.gcloud',
    '__MACOSX'
}

# Specific filenames that should be excluded from the entire process.
CORE_IGNORE_FILES = set()

# Files with these extensions will have their names listed in the project tree,
# but their actual content will be skipped.
CORE_SKIP_EXTS = {
    # Data & Databases
    '.pbix', '.db', '.sqlite', '.sqlite3', '.parquet', '.pkl', '.pickle', '.feather', '.h5',
    # Compressed & Binary
    '.zip', '.tar', '.gz', '.7z', '.rar', '.exe', '.dll', '.so', '.bin',
    # Media
    '.png', '.jpg', '.jpeg', '.gif', '.svg', '.pdf', '.mp4', '.mp3', '.mov',
    # Environment & Secrets
    '.env', '.venv', '.pyc', '.ds_store'
}

# Default values for CLI arguments and processing functions
DEFAULT_CSV_SAMPLE_SIZE = 35           # Controls the number of rows per csv file.
DEFAULT_SQL_SAMPLE_SIZE = 35           # Controls the number of INSERT/data rows kept per table in SQL files.
DEFAULT_SQL_MAX_LINES = 50             # Caps the total number of non-data lines (comments, setup, etc.) in SQL files.
DEFAULT_MAX_LINES = 55                 # Max lines of text output to keep per notebook cell.
DEFAULT_MAX_SHEETS = 10                # Max number of sheets to process in Excel files.
DEFAULT_SEED = 42                      # Random seed for consistent sampling.
DEFAULT_MAX_FILE_SIZE_KB = 70          # maximum file size of unhandled type to keep enitrely (if file is larger than that only the first 10kb will be shown)
DEFAULT_OUTPUT_FILE = 'PROMPT.md'      # default .md file output name

# A unique identifier added to the top of every generated Markdown file.
GENERATION_FLAG = "this markdown was generated by data2prompt".upper()

# --- UI & Aesthetic Constants ---
MATRIX_DARK_GREEN = (0, 150, 0)
MATRIX_NEON_GREEN = (0, 255, 0)
STARTUP_ANIMATION_DURATION = 0.9
ANIMATION_FRAME_DELAY = 0.03

# Scroll Bar Characters
SCROLL_THUMB = "█"
SCROLL_TRACK = "│"
